### ISSUE TITLE
Wallet state diagrams

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#253]
Add wallet state transition diagrams to documentation. Cover all states and conditions required to move between states.

**Comment by michalinacienciala** [comment]
[state_transition.pdf](https://github.com/keep-network/tbtc-v2/files/8619260/state_transition.pdf)
@pdyraga This is what I have so far. Couple of questions:
1. Would you like me to use the `MovingFunds` notation instead of `MOVING_FUNDS`, as in contracts?
2. Would you like me to use the `notifyWalletClosingPeriodElapsed` notation instead of `notify wallet exceeding closing period`, as in contracts?
3. Would you like me to include on the picture all the possible functions to be called for each state?
4. Anything else you would like me to change?
5. What do you think about storing the source code and PNG files in `tbtc-v2/docs/diagrams`? So far I have the system flow placed in `keep-core/docs/`, but keeping it in some subdirectory (like `keep-core/docs/diagrams)`seems to be a good idea.

**Comment by pdyraga** [comment]
> * Would you like me to use the `MovingFunds` notation instead of `MOVING_FUNDS`, as in contracts?

I think capital letters are fine as long as we'll use them consistently across the documentation and diagrams.

> * Would you like me to use the `notifyWalletClosingPeriodElapsed` notation instead of `notify wallet exceeding closing period`, as in contracts?

Let's use the name of the function from `Bridge.sol` moving the wallet to the given state.

> * Would you like me to include on the picture all the possible functions to be called for each state?

Not sure if on the picture with state transitions but I think a list of them below the state transition diagram would be awesome. On the state transition diagram, I would only include functions that are moving wallet from one state to another

> * Anything else you would like me to change?

LIVE never goes to CLOSED directly now. They go to CLOSING.

> * What do you think about storing the source code and PNG files in `tbtc-v2/docs/diagrams`? So far I have the system flow placed in `keep-core/docs/`, but keeping it in some subdirectory (like `keep-core/docs/diagrams)`seems to be a good idea.

Sure, we can always refer them from documents placed in `docs` then.
