### ISSUE TITLE
Staker rewards

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#38]
In tBTC v2, signers will be rewarded continuously. 

@eth-r proposed to implement the following algorithm on the top of the sortition pool:
- we keep a monotonously increasing counter of weight-seconds of the pool `P`
- this is updated by multiplying the total weight of the pool with the number of seconds since the last update, whenever the pool weight changes
- we keep a monotonously increasing counter of total rewards paid into the pool `R`
- this is updated whenever rewards are paid in
- each operator tracks the amount of weight-seconds they've contributed to the pool `W`
- they also track the amount of total rewards that had accumulated in the pool when they last withdrew rewards `Rw`, and the amount of weight-seconds they had contributed at that time `Ww`, and the total weight-seconds in the pool at that time `Pw`

when an operator withdraws rewards, we take the amount of newly accumulated rewards in the pool since their last withdrawal `R - Rw`, calculate their contribution to the accumulated weight-seconds in that time `W - Ww / P - Pw`, and multiply the reward difference with the contribution fraction

then we update `Rw = R, Ww = W, Pw = P`

when an operator joins the pool, we probably need to do a synchronisation step where we add and withdraw imaginary rewards that equal the amount the operator would've received if they had been present in the pool right from the beginning:

T = 0:Alice joins the pool with 100 weight
T = 10: 20 rewards are paid in
T = 20: Bob joins the pool with 50 weight; the pool has 2,000 weight-seconds and 20 rewards accumulated, and Bob's weight is 50% of the current weight so we add 50% to both the weight-seconds and accumulated rewards, setting them to 3,000 and 30 respectively, and record that Bob "withdrew" when `P = 3,000; R = 30` having "contributed" `W = 1,000`
T= 30: Alice withdraws rewards, `P = 4,500 and Alice's W = 3,000`, so Alice gets 2/3 of the "accumulated" 30 rewards = 20 rewards are paid out to Alice
T = 40: 30 rewards are paid in, `R = 60`
T = 50: Bob withdraws rewards, `P = 7,500` and Bob's `W = 2,500`; because Bob's `Ww = 1,000; Rw = 30, Pw = 3,000` we get a difference of 1,500 contributed weight-seconds, 30new reward accumulation, and 4,500accumulated weight-seconds poolwide, thus Bob withdraws `(1,500 / 4,500) * 30 = 10` rewards

We need to analyze and further spec the approach. We also need to define what is happening during slashing and when someone is removed from the pool as a result of inactivity. We could also see if the design of [LP rewards](https://github.com/keep-network/keep-ecdsa/blob/main/solidity/contracts/LPRewards.sol) or [cov pool rewards](https://github.com/keep-network/coverage-pools/blob/main/contracts/RewardsPool.sol) could help us somehow.

**Comment by eth-r** [comment]
The unipool (LP rewards) approach isn't bad, it's fairly simple in implementation (only need to track "accumulated rewards per weight" globally and "rewards per weight withdrawn" per operator) and whenever rewards are paid in they're essentially distributed evenly to all current members based on their current weight. Not as sophisticated as a fully weight-seconds adjusted approach but fairly reasonable if rewards are paid out often enough. A downside is that we can't get historical data without adding extra complexity so some corrections to the reward payments may be difficult to implement (e.g. in the case of inactive operators, so we'd need to kick them and prevent them from re-joining for a time, and then they'd miss the rewards paid during the time they're out).

I'm suspecting that a fully weight-second based approach may not work with just a single global tracker and could instead require iterating over reward intervals (all intervals within an e.g. 7 day period are distributed to operators based on weight-seconds they contributed within that period) or individual reward payments (each payment is distributed based on weight-seconds since the previous payment) which could get expensive to operators (the 7 day period version less so). The unipool approach might

**Comment by beaushinkle** [comment]
implemented in https://github.com/keep-network/sortition-pools/pull/130
