### ISSUE TITLE
Cross-chain Tokenized Threshold BTC: Deploy Threshold Council multisig on L2s

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#549]
See https://github.com/keep-network/tbtc-v2/pull/542

The Governance in the initial implementation should be based on Gnosis Safe 6-of-9 Threshold Council Multisig. Since the Gnosis Safe for Threshold Council was deployed using Safe Proxy factory v1.3.0, it [should be possible](https://help.safe.global/en/articles/5267779-i-sent-assets-to-a-safe-address-on-the-wrong-network-any-chance-to-recover) to replay the same transaction creating Gnosis Safe with the same address on the supported L2s and sidechains.

This issue is about deploying the safe and testing it on:
- [x] Arbitrum
- [x] Polygon
- [x] Optimism

Ideally please use the Keep deployer account for this work.

**Comment by cygnusv** [comment]
> it [should be possible](https://help.safe.global/en/articles/5267779-i-sent-assets-to-a-safe-address-on-the-wrong-network-any-chance-to-recover) to replay the same transaction creating Gnosis Safe with the same address on the supported L2s and sidechains.

It seems it will be possible for Polygon and Arbitrum, but not so sure for Optimism, as it uses a different proxy factory. Investigating this.

> The Governance in the initial implementation should be based on Gnosis Safe 6-of-9 Threshold Council Multisig. 

There's an added complication here. Redeploying the Council MS in other chains (even if it's technically possible), would recreate the initial MS setting, with the first 9 owners and a 9-of-9 configuration. 

E.g., I just simulated for Polygon, and while the resulting MS address is the same, the configuration is the initial 9-of-9:

`0x9f6e831c8f8939dc0c830c6e492e7cef4f9c2f5f.setup
(_owners = ["0xfe45baf0f18c207152a807c1b05926583cfe2e4b","0xce1a723b066b2012550fb473558d6de681f8b5f7","0x1549707126b04199bc65a7a1f94a149fa9915771","0x535ab354fa5a8247d45b28502cc751427f9c7896","0x421a8400049f6d832c9234ed5fdeedd195a4dab5","0x5805b9ef3a7e6b26b8cf1cea42b06efe598c526a","0x2844a0d6442034d3027a05635f4224d966c54fd7","0x13f026559e3cb36008178e7e358401d6ed4d6743","0x8d855ac1c48c953d78b678dcc9b346c59a54dcc9"], _threshold = 9`

We'd need to coordinate TXs with some ex-council members, on different chains, so that's an additional challenge.

**Comment by mswilkison** [comment]
The former signers are:
0xce1a723b066b2012550fb473558d6de681f8b5f7
0x5805b9ef3a7e6b26b8cf1cea42b06efe598c526a
0x13f026559e3cb36008178e7e358401d6ed4d6743

The rest are all current signers. I'll try to verify if the former ones are still available for this.

**Comment by mswilkison** [comment]
I was able to confirm all the former signers are available so we can proceed on this whenever it makes sense.

**Comment by pdyraga** [comment]
@cygnusv Any update on Optimism council safe? We deployed contracts to Arbitrum last week (https://github.com/keep-network/tbtc-v2/issues/577) and are now looking into the Optimism deployment.

**Comment by derekpierre** [comment]
Gnosis currently uses 2 different addresses for their factory contracts. Optimism used a different factory contract than mainnet, polygon, and arbitrum. This seems to be the root cause of the UI issues when trying to use the same safe address on Optimism. 

Given that the UI is unusable when attempting to reuse the same safe address (`0x9F6e831c8F8939DC0C830C6e492e7cEf4f9C2F5f`), we created a new Optimism Council safe:
* https://app.safe.global/settings/setup?safe=oeth:0x7fB50BBabeDEE52b8760Ba15c0c199aF33Fc2EfA

The relevant Council owners were set (https://app.safe.global/oeth:0x7fB50BBabeDEE52b8760Ba15c0c199aF33Fc2EfA/transactions/tx?id=multisig_0x7fB50BBabeDEE52b8760Ba15c0c199aF33Fc2EfA_0xdf536dca983824e3708640b6ec7302ce5edf18f163b759070888796632654e08) and the threshold was set to 6/9 through a separate tx requiring all owners to sign (https://app.safe.global/oeth:0x7fB50BBabeDEE52b8760Ba15c0c199aF33Fc2EfA/transactions/tx?id=multisig_0x7fB50BBabeDEE52b8760Ba15c0c199aF33Fc2EfA_0x24198c20f52b259f04e499d8fcb17f3a28a6be0c1246a5eb01edc7b3305f9b13).

**Comment by derekpierre** [comment]
^ The new safe address ([0x7fB50BBabeDEE52b8760Ba15c0c199aF33Fc2EfA](https://app.safe.global/settings/setup?safe=oeth:0x7fB50BBabeDEE52b8760Ba15c0c199aF33Fc2EfA)) was used for the Optimism Grant application: https://gov.optimism.io/t/draft-gf-phase-1-growth-experiments-grant-btc-holders-bridge-to-ethereum-in-a-trust-minimized-way/5638

**Comment by derekpierre** [comment]
> Make sure the threshold is properly set for all deployed safes. Most of them are still 9/9.
> Make sure the signer addresses are all the same. For instance, signer 0x13F026559e3Cb36008178e7e358401d6Ed4d6743 from [Arbitrum safe](https://app.safe.global/settings/setup?safe=arb1:0x9F6e831c8F8939DC0C830C6e492e7cEf4f9C2F5f) is not present in [Ethereum L1 council multisig](https://app.safe.global/settings/setup?safe=eth:0x9f6e831c8f8939dc0c830c6e492e7cef4f9c2f5f)

Just to clarify, for the non-Optimism Council safes i.e. the safes that mantained the same ETH L1 address `0x9F6e831c8F8939DC0C830C6e492e7cEf4f9C2F5f`. Those could only be initiated/created with the same original Threshold Council signers i.e. the signers when the Council was first initiated/created. 

Therefore the plan was to first reduce the threshold from 9 to 3, so that we can quickly get the safe set up appropriately using only a very small subset of the original signers to quickly execute the multiple txs needed to modify the composition of signers to match the current set and signing threshold. This was to minimize any issues.

If this is now a priority we can work to get the signing/setup resolved as part of the linked issue (cc @cygnusv ).

**Comment by pdyraga** [comment]
This totally makes sense and it was expected that they will be 9/9 initially. I think we should bring them to the same threshold as on L1 so hence the follow-up issue #600. I'd prefer doing it now before the first tBTC crosses the bridge with Wormhole.
