### ISSUE TITLE
User acceptance tests of redemptions veto mechanism (TIP-072)

### ISSUE THREAD

**Issue by lukasz-zimnoch** [keep-network/tbtc-v2#782]
Depends on: https://github.com/keep-network/tbtc-v2/issues/781

The scope of this issue includes the design and execution of the user acceptance tests for the redemptions veto mechanism specified in [TIP-072: Optimistic redemptions](https://forum.threshold.network/t/tip-072-optimistic-redemptions/793) and developed as part of https://github.com/keep-network/tbtc-v2/issues/781. UATs should be executed on Sepolia testnet once necessary contract upgrades are deployed there.
```[tasklist]
### Tasks
- [x] Design UAT scenarios according to the TIP-072 specification
- [x] Execute designed UAT scenarios
```

**Comment by michalinacienciala** [comment]
### Scenarios [WIP]

This task is about testing the new redemption veto mechanism by executing UAT scenarios mentioned below. UATs should be executed on Sepolia testnet once necessary contract upgrades are deployed there. The value of the governable parameters may get modified on the testnet in order to make testing faster.

#### Scenario 1

Checking regular redemption without objections.

| Step      | Expected result                                                                                                                                                                                                                         |
| --------- | -------------- | 
| Trigger a redemption of a deposit (at T0). Do not object the redemption.                                                                                                                   |                                                                                                                                                                                                                                         |
| Wait till T1=T0+2h.                                                                                                                                                                        | The redemption should start being executed at T1. Once redemption is processed, the BTC should be returned to the requested BTC address (returned amount of BTC should equal to the amount of TBTC minus Threshold Network fee).        |

#### Scenario 2

Checking redemption with one objection.

| Step      | Expected result                                                                                                                                                                                                                         |
| --------- | -------------- | 
| Trigger a redemption of a deposit (at T0).                                                                                                                                                 |                                                                                                                                                                                                                                         |
| Some time later (<T0+2h, at T1) make one Guardian object to the redemption.                                                                                                                |                                                                                                                                                                                                                                         |
| Wait till T2=T0+2h.                                                                                                                                                                        | The redemption should start being executed at T2. Once redemption is processed, the BTC should be returned to the requested BTC address (returned amount of BTC should equal to the amount of TBTC minus Threshold Network fee).        |

#### Scenario 3

Checking redemption with two objections.

| Step      | Expected result                                                                                                                                                                                                                         |
| --------- | -------------- | 
| Trigger a redemption of a deposit (at T0).                                                                                                                                                 |                                                                                                                                                                                                                                         |
| Some time later (<T0+2h, at T1) make one Guardian object to the redemption.                                                                                                                |                                                                                                                                                                                                                                         |
| Some time later (<T0+8h, at T2) make another Guardian object to the redemption.                                                                                                            |                                                                                                                                                                                                                                         |
| Wait till T3=T0+8h.                                                                                                                                                                        | At T3=T0+24h the redemption should start being executed. Once redemption is processed, the BTC should be returned to the requested BTC address (returned amount of BTC should equal to the amount of TBTC minus Threshold Network fee). |

#### Scenario 4

Checking redemption with three objections. Making sure each objection extends the redemption request period. Ensuring redemption gets vetoed. Checking if amount of the vetoed redemption gets freezed for 1 month.

| Step      | Expected result                                                                                                                                                                                                                         |
| --------- | -------------- | 
| Trigger a redemption of a deposit (at T0). Make sure requested redeem amount (X) is at least 0.015 tBTC smaller that the max redeem amount (Y).                                            | 1 tBTC. Request redem of 0.8. 0.2 (Y-X) still left for redemption.                                                                                                                                                                      |
| Some time later (<T0+2h, at T1) make one Guardian object to the redemption.                                                                                                                |                                                                                                                                                                                                                                         |
| Some time later (<T0+8h, at T2; T2>T1+2h) make another Guardian object to the redemption.                                                                                                  |                                                                                                                                                                                                                                         |
| Some time later (<T0+24h, at T3, T3>T2+8h) make another Guardian object to the redemption.                                                                                                 | At T3 the redemption veto should start being executed. Once veto is processed, the amount of tBTC belonging to the redemption requester should decrease by <penalty_amunt>.                                                             |
| Some time later (<T3+1month, at T4) using the same redeemer try to redeem amount that's bigger than Y-X.                                                                                   | Redemption should not be possible.                                                                                                                                                                                                      |
| Some time later (<T3+1month, at T5) using the same redeemer try to redeem amount Z that's smaller or equal to Y-X.                                                                         | Redemption should be requested.                                                                                                                                                                                                         |
| Some time later (<T3+1month, at T5) using the same redeemer try to redeem amount that's bigger than Y-X-Z.                                                                                 | Redemption should not be possible.                                                                                                                                                                                                      |
| Wait till T6=T3+1month. Using the same redeemer try to redeem amount that's bigger than Y-X-Z.                                                                                             | Redemption freeze window should be over, redemption should be successfully requested.                                                                                                                                                   |

#### Scenario 5

Making sure that freeze window is specific to a given redemption and does not get extended when another redemption gets vetoed (or does not end when other redemption freeze window ends).

| Step      | Expected result                                                                                                                                                                                                                         |
| --------- | -------------- | 
| Let Y be your max redemption balance. Requests two redemptions using the same account, one after another (X1 - amount of the first redemption, X2 amount of the second redemption).        |                                                                                                                                                                                                                                         |
| Make three objections to the both redemptions, triggiering veto for both of them. Let T1 be the time of the veto of the first redemption, T2 - time of the veto of the second redemption.  |                                                                                                                                                                                                                                         |
| At T3, where T1+1month<T3<T2+1month try to redeem more than Y-X2.                                                                                                                          | Redemption should not be possible.                                                                                                                                                                                                      |
| At T4, where T1+1month<T4<T2+1month try to redeem Y-X2 or less.                                                                                                                            |                                                                                                                                                                                                                                         |
| At T5, where T1+1month<T5<T2+1month try to redeem X2.                                                                                                                                      | Redemption should not be possible.                                                                                                                                                                                                      |
| At T4, where T4>T2+1month try to redeem X2.                                                                                                                                                | Redemption should be requested.                                                                                                                                                                                                         |

#### Additional requirements and caveats
- Record all errors logged by client nodes during scenario execution. Temporary communication errors can always happen but they should not lead to scenario failure
- Make sure client nodes do not panic unexpectedly at any stage

**Comment by michalinacienciala** [comment]
We're also executing Scenario 4 again, this time with the value of governable parameters almost the same as the default ones:
* redemption request period is `2 hours`
* redemption request period after one veto gets extended to `8 hours`
* redemption request period after two vetos gets extended to `24 hours`
* freeze time upon veto is ~~`1 month`~~ `24 hours`

Additionally a `waivedAmountLimit ` parameter was configured to `0.02` value (redemptions smaller than this value cannot be vetoed).

#### Scenario 4 (in progress)

| Step      | Expected result      | Test execution / result |
| --------- | -------------- | -- |
| Trigger a redemption of a deposit (at T0). Make sure requested redeem amount (X) is at least 0.015 tBTC smaller that the max redeem amount (Y).   |   | Redemption of XYZ tBTC requested from account `XYZ` to BTC address `XYZ` at XYZ (T0). [Unmint tx](XYZ). |
| Some time later (<T0+2h, at T1) make one Guardian object to the redemption.   |   | 1st objection raised at XYZ (T1). [Objection tx](XYZ). |
| Some time later (<T0+8h, at T2; T2>T1+2h) make another Guardian object to the redemption. | | 2nd objection raised at XYZ (T2). [Objection tx](XYZ). |
| Some time later (<T0+24h, at T3, T3>T2+8h) make another Guardian object to the redemption. | At T3 the redemption veto freeze period should start. | 3rd objection raised at XYZ (T3). [Objection tx](XYZ). |
| Some time later (<T3+24h, at T4) using the same redeemer try to request another redemption.     | Redemption should not be possible.  | At XYZ (T4) tried redeeming XYZ to `XYZ` using the account `XYZ`. Got error: `Redemption request rejected by the watchtower`. |
| Soon after try to retrieve the vetoed funds.   | Retrieval should not be possible.   | Tried to retrieve funds at XYZ. Transaction failed with the `Freeze period not expired` error. [Retrieve tx](XYZ). |
| Wait till T5>T3+24h. Try to retrieve the vetoed funds.   | The funds (decreased by `penalty_factor` of the requested redemption amount) should be retrieved as a TBTC Bank balance.  | Tried to retrieve funds at XYZ (T5). Transaction succeeded. Bank balance of retriever after transaction was increased by XYZ (95% of XYZ). [Retrieve tx](XYZ). No BTC was returned. |

**Comment by michalinacienciala** [comment]
All tests have passed.
@lukasz-zimnoch, you can change the freeze time upon veto param back to 1 month.
